language: python
  - "2.7"
dist: trusty

before_install:
    - sudo apt-get install mercurial darcs bzr

install:
  - sudo pip install cherrypy jinja2 codecov

before_script:
  - echo "[ui]" > $HOME/.hgrc
  - echo "username = John Doe  <jon@exmple.com>" >> $HOME/.hgrc
  - bzr whoami "Your Name <name@example.com>"

script:
  - coverage run test.py

after_script:
    # Report coverage results to codecov.io
    # and export tox environment variables
    - codecov
