language: python
  - "2.7"
dist: trusty

before_install:
    - sudo apt-get install mercurial darcs bzr

install:
  - sudo pip install cherrypy jinja2 scrutinizer-ocular
  - wget http://www.monotone.ca/downloads/1.0/mtn-1.0-linux-x86.bz2
  - bzip2 -d mtn-1.0-linux-x86.bz2
  - sudo mv mtn-1.0-linux-x86 /usr/bin/mtn
  - sudo chmod +x /usr/bin/mtn

before_script:
  - echo "[ui]" > $HOME/.hgrc
  - echo "username = John Doe  <jon@exmple.com>" >> $HOME/.hgrc
  - bzr whoami "Your Name <name@example.com>"

script:
  - PATH=$PATH:$HOME/bin coverage run test.py

after_script:
    - ocular # Send reports to Scrutinizer
